Given N battlefields and S soldiers, the number of possible distributions of soldiers is 
$${N + S - 1 \choose N - 1}$$
By partitioning on the number of soldiers on the first battlefield and letting $s$ be the number of soldiers in the remaining $N-1$ battlefields, we note
$$
{N + S - 1 \choose N - 1} = \sum_{s = 0}^S {N + s - 2 \choose N - 2}
$$
We can hence extract the number of soldiers on the first battlefield. Then we proceed recursively. For example, for $(N, S) = (3,4)$, we have $15$ possibilities. Let $i$ denote the index.


If $i < {N - 2 \choose N - 2} = 1$, we know the first battlefield contains all soldiers.

Elif $i < 1 + {N + 1 - 2 \choose N - 2} = 1 + 2$, we know the first battlefield all but one soldiers.

Elif $i < 1 + 2 + {N + 2 - 2 \choose N - 2} = 1 + 2 + 3$, we know the first battlefield all but two soldiers.

etc. Once we know the amount of soldiers in the first battlefield, we call the function on $(N-1, S-s)$.

For example, if $i=4$, we see that the first battlefield has 2 solders. We then set $i = i- 3=1$ and run the function on $(2, 2)$ so we know that the second battlefield has 1 soldier.





Now we find the NE

In [1]:
from infrastructure import find_CE
from Blotto_infra import *
import  numpy as np

In [2]:
def soldier_dist(i, N, S, out):
    if S == 0:
        out += [0] * N
        return np.array(out)
    if N == 1:
        out.append(S)
        return np.array(out)

    temp = 1
    for s in range(S + 1):
        if s >= 1:
            temp = (temp * (N + s - 2)) // s
        if temp > i:
            out.append(S - s)
            return soldier_dist(i, N - 1, s, out)
        else:
            i -= temp
soldier_dist(935, 5, 10, [])

array([ 0,  0, 10,  0,  0])

In [5]:
Single_Evaluation(Blotto(3, (7, 7)), 10000).viable_strategies(eps=0.01)

Viable strategies for agent 0:
	 Probability of playing [5 2 0] is 0.024.
	 Probability of playing [5 0 2] is 0.017.
	 Probability of playing [4 3 0] is 0.061.
	 Probability of playing [4 2 1] is 0.062.
	 Probability of playing [4 1 2] is 0.077.
	 Probability of playing [4 0 3] is 0.076.
	 Probability of playing [3 4 0] is 0.062.
	 Probability of playing [3 0 4] is 0.062.
	 Probability of playing [2 5 0] is 0.025.
	 Probability of playing [2 4 1] is 0.089.
	 Probability of playing [2 1 4] is 0.077.
	 Probability of playing [2 0 5] is 0.013.
	 Probability of playing [1 4 2] is 0.078.
	 Probability of playing [1 2 4] is 0.088.
	 Probability of playing [0 5 2] is 0.021.
	 Probability of playing [0 4 3] is 0.053.
	 Probability of playing [0 3 4] is 0.069.
	 Probability of playing [0 2 5] is 0.029.




Viable strategies for agent 1:
	 Probability of playing [5 2 0] is 0.033.
	 Probability of playing [5 0 2] is 0.021.
	 Probability of playing [4 3 0] is 0.068.
	 Probability of playing [4 2 1

In [5]:
find_CE(Blotto(3, (7, 7)), iterations=10000)

In [4]:
soldier_dist(6, 3, 7, [])

array([4, 3, 0])

In [5]:
e = Evaluation(Blotto(3,5), 1000000, 10)
e.average_strategy

KeyboardInterrupt: 

In [ ]:
np.round(e.average_strategy, 4)

array([0.    , 0.    , 0.    , 0.112 , 0.1125, 0.109 , 0.1086, 0.    ,
       0.    , 0.1115, 0.    , 0.1132, 0.    , 0.113 , 0.    , 0.    ,
       0.    , 0.1115, 0.1087, 0.    , 0.    ])

In [ ]:
np.round(e.sds, 4) * 2

array([[0.    , 0.    , 0.    , 0.0104, 0.0096, 0.011 , 0.0112, 0.    ,
        0.    , 0.008 , 0.    , 0.0086, 0.    , 0.0078, 0.    , 0.    ,
        0.    , 0.0074, 0.011 , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.015 , 0.0104, 0.0098, 0.0116, 0.    ,
        0.    , 0.0114, 0.    , 0.0056, 0.    , 0.0084, 0.    , 0.    ,
        0.    , 0.0076, 0.0116, 0.    , 0.    ]])

In [ ]:
find_Nash(Blotto(3,5), iterations=15000000)

Utility of Agent 0 is -3526
[0.    0.    0.    0.109 0.112 0.112 0.112 0.    0.    0.109 0.    0.112
 0.    0.112 0.    0.    0.    0.109 0.112 0.    0.   ]
Utility of Agent 1 is 3526
[0.    0.    0.    0.102 0.12  0.108 0.111 0.    0.    0.108 0.    0.118
 0.    0.114 0.    0.    0.    0.104 0.115 0.    0.   ]


In [ ]:
N=3
S=3
comb(N + S -1, N-1)

10

In [ ]:
import numpy as np

In [ ]:
arr =np.array([np.array([np.array([1,2,3]), np.array([4,5,6])]), np.array([np.array([1,2,3]) + 1, np.array([4,5,6]) + 2])] )
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [6, 7, 8]]])

In [ ]:
np.std(arr, axis=0)

array([[0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])