Given N battlefields and S soldiers, the number of possible distributions of soldiers is 
$${N + S - 1 \choose N - 1}$$
By partitioning on the number of soldiers on the first battlefield and letting $s$ be the number of soldiers in the remaining $N-1$ battlefields, we note
$$
{N + S - 1 \choose N - 1} = \sum_{s = 0}^S {N + s - 2 \choose N - 2}

$$
We can hence extract the number of soldiers on the first battlefield. Then we proceed recursively. For example, for $(N, S) = (3,4)$, we have $15$ possibilities. Let $i$ denote the index.


If $i < {N - 2 \choose N - 2} = 1$, we know the first battlefield contains all soldiers.

Elif $i < 1 + {N + 1 - 2 \choose N - 2} = 1 + 2$, we know the first battlefield all but one soldiers.

Elif $i < 1 + 2 + {N + 2 - 2 \choose N - 2} = 1 + 2 + 3$, we know the first battlefield all but two soldiers.

etc. Once we know the amount of soldiers in the first battlefield, we call the function on $(N-1, S-s)$.

For example, if $i=4$, we see that the first battlefield has 2 solders. We then set $i = i- 3=1$ and run the function on $(2, 2)$ so we know that the second battlefield has 1 soldier.





Now we find the NE

In [1]:
from infrastructure import find_Nash
from Blotto_infra import *
import  numpy as np

In [2]:
def soldier_dist(i, N, S, out):
    if S == 0:
        out += [0] * N
        return np.array(out)
    if N == 1:
        out.append(S)
        return np.array(out)

    temp = 1
    for s in range(S + 1):
        if s >= 1:
            temp = (temp * (N + s - 2)) // s
        if temp > i:
            out.append(S - s)
            return soldier_dist(i, N - 1, s, out)
        else:
            i -= temp
soldier_dist(935, 5, 10, [])

array([ 0,  0, 10,  0,  0])

In [12]:
find_Nash(Blotto(3, 7), iterations=500000)

array([[1.11110889e-07, 1.11110889e-07, 1.11110889e-07, 3.48171834e-02,
        1.26312789e-03, 3.67686630e-02, 6.28665141e-02, 6.44150516e-02,
        6.60123419e-02, 6.60426023e-02, 6.78083621e-02, 3.17786776e-06,
        5.89442741e-04, 5.65349499e-06, 6.03349348e-02, 3.47967298e-02,
        6.73609070e-02, 4.71866937e-04, 3.96452908e-04, 6.65314602e-02,
        3.76265001e-02, 1.11110889e-07, 7.05511935e-04, 6.05559142e-02,
        4.98583495e-06, 6.74429012e-02, 9.27328294e-05, 1.98067237e-07,
        1.11110889e-07, 1.11110889e-07, 3.72099686e-02, 6.47537665e-02,
        6.38669256e-02, 3.72552343e-02, 1.11110889e-07, 1.11110889e-07],
       [1.66161284e-07, 5.10478777e-07, 1.66161284e-07, 4.17361625e-02,
        3.39016488e-04, 4.32183879e-02, 6.20431167e-02, 6.04593758e-02,
        6.44833164e-02, 6.23898508e-02, 6.07110424e-02, 3.54369392e-06,
        2.31655253e-04, 4.10054056e-06, 5.85069777e-02, 4.16552170e-02,
        6.81200088e-02, 3.14621244e-04, 6.82491460e-05, 6.70547

In [11]:
soldier_dist(6, 3, 7, [])

array([4, 3, 0])

In [14]:
e = Evaluation(Blotto(3,5), 1000000, 10)
e.average_strategy

array([7.29518666e-08, 2.71312253e-06, 1.88248393e-06, 1.11972722e-01,
       1.12453883e-01, 1.09024210e-01, 1.08612009e-01, 3.26632392e-06,
       3.25896130e-06, 1.11474373e-01, 1.86679395e-06, 1.13200066e-01,
       4.16092031e-06, 1.13041564e-01, 2.55820445e-06, 6.84335377e-08,
       1.90967112e-06, 1.11473296e-01, 1.08723392e-01, 2.66590711e-06,
       5.95237500e-08])

In [18]:
np.round(e.average_strategy, 4)

array([0.    , 0.    , 0.    , 0.112 , 0.1125, 0.109 , 0.1086, 0.    ,
       0.    , 0.1115, 0.    , 0.1132, 0.    , 0.113 , 0.    , 0.    ,
       0.    , 0.1115, 0.1087, 0.    , 0.    ])

In [17]:
np.round(e.sds, 4) * 2

array([[0.    , 0.    , 0.    , 0.0104, 0.0096, 0.011 , 0.0112, 0.    ,
        0.    , 0.008 , 0.    , 0.0086, 0.    , 0.0078, 0.    , 0.    ,
        0.    , 0.0074, 0.011 , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.015 , 0.0104, 0.0098, 0.0116, 0.    ,
        0.    , 0.0114, 0.    , 0.0056, 0.    , 0.0084, 0.    , 0.    ,
        0.    , 0.0076, 0.0116, 0.    , 0.    ]])

In [11]:
find_Nash(Blotto(3,5), iterations=15000000)

Utility of Agent 0 is -3526
[0.    0.    0.    0.109 0.112 0.112 0.112 0.    0.    0.109 0.    0.112
 0.    0.112 0.    0.    0.    0.109 0.112 0.    0.   ]
Utility of Agent 1 is 3526
[0.    0.    0.    0.102 0.12  0.108 0.111 0.    0.    0.108 0.    0.118
 0.    0.114 0.    0.    0.    0.104 0.115 0.    0.   ]


In [5]:
N=3
S=3
comb(N + S -1, N-1)

10

In [1]:
import numpy as np

In [14]:
arr =np.array([np.array([np.array([1,2,3]), np.array([4,5,6])]), np.array([np.array([1,2,3]) + 1, np.array([4,5,6]) + 2])] )
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [6, 7, 8]]])

In [15]:
np.std(arr, axis=0)

array([[0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])