Given N battlefields and S soldiers, the number of possible distributions of soldiers is 
$${N + S - 1 \choose N - 1}$$
By partitioning on the number of soldiers on the first battlefield and letting $s$ be the number of soldiers in the remaining $N-1$ battlefields, we note
$$
{N + S - 1 \choose N - 1} = \sum_{s = 0}^S {N + s - 2 \choose N - 2}
$$
We can hence extract the number of soldiers on the first battlefield. Then we proceed recursively. For example, for $(N, S) = (3,4)$, we have $15$ possibilities. Let $i$ denote the index.


If $i < {N - 2 \choose N - 2} = 1$, we know the first battlefield contains all soldiers.

Elif $i < 1 + {N + 1 - 2 \choose N - 2} = 1 + 2$, we know the first battlefield all but one soldiers.

Elif $i < 1 + 2 + {N + 2 - 2 \choose N - 2} = 1 + 2 + 3$, we know the first battlefield all but two soldiers.

etc. Once we know the amount of soldiers in the first battlefield, we call the function on $(N-1, S-s)$.

For example, if $i=4$, we see that the first battlefield has 2 solders. We then set $i = i- 3=1$ and run the function on $(2, 2)$ so we know that the second battlefield has 1 soldier.





Now we find the NE

In [1]:
from infrastructure import find_CE
from Blotto_infra import *
import numpy as np

In [2]:
Single_Evaluation(Blotto(5, (7, 7)), 15000).viable_strategies(eps=0.01)

Viable strategies for agent 0:
	 Probability of playing [3 3 0 0 1] is 0.011.
	 Probability of playing [3 2 2 0 0] is 0.015.
	 Probability of playing [3 2 0 2 0] is 0.013.
	 Probability of playing [3 2 0 0 2] is 0.013.
	 Probability of playing [3 1 3 0 0] is 0.01.
	 Probability of playing [3 1 0 3 0] is 0.011.
	 Probability of playing [3 0 2 2 0] is 0.01.
	 Probability of playing [3 0 2 0 2] is 0.01.
	 Probability of playing [3 0 0 2 2] is 0.012.
	 Probability of playing [2 3 2 0 0] is 0.012.
	 Probability of playing [2 3 1 0 1] is 0.01.
	 Probability of playing [2 3 0 0 2] is 0.015.
	 Probability of playing [2 2 3 0 0] is 0.017.
	 Probability of playing [2 2 2 0 1] is 0.017.
	 Probability of playing [2 2 1 0 2] is 0.01.
	 Probability of playing [2 2 0 3 0] is 0.016.
	 Probability of playing [2 2 0 0 3] is 0.012.
	 Probability of playing [2 1 2 2 0] is 0.01.
	 Probability of playing [2 0 3 0 2] is 0.012.
	 Probability of playing [2 0 2 1 2] is 0.01.
	 Probability of playing [2 0 1 2 2]

In [4]:
Single_Evaluation(Collapsed_Blotto(5, (7, 7)), 300000).viable_strategies(eps=0.02)

Viable strategies for agent 0:
	 Probability of playing [0 0 1 3 3] is 0.475.
	 Probability of playing [0 0 2 2 3] is 0.153.
	 Probability of playing [0 1 2 2 2] is 0.252.
	 Probability of playing [1 1 1 1 3] is 0.055.
	 Probability of playing [1 1 1 2 2] is 0.06.




Viable strategies for agent 1:
	 Probability of playing [0 0 1 3 3] is 0.213.
	 Probability of playing [0 0 2 2 3] is 0.399.
	 Probability of playing [0 1 1 2 3] is 0.072.
	 Probability of playing [0 1 2 2 2] is 0.035.
	 Probability of playing [1 1 1 1 3] is 0.081.
	 Probability of playing [1 1 1 2 2] is 0.198.






In [ ]:
import numpy as np

In [ ]:
arr =np.array([np.array([np.array([1,2,3]), np.array([4,5,6])]), np.array([np.array([1,2,3]) + 1, np.array([4,5,6]) + 2])] )
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [6, 7, 8]]])

In [ ]:
np.std(arr, axis=0)

array([[0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

We can collapse the number of strategies by arguing that to an agent, the order of the battlefields do not matter. Hence, letting the total number of partitions of $S$ soldiers into $N$  battlefields be $P_N(S)$, we have
$$
P_N(S) = P_{N-1}(S) + P_{N-1}(S-N) + P_{N-1}(S-2) +...
$$
where $P_n(0)=1$ and $P_n(M)=0$ for $M<0$


In [2]:
partition_matrix(3, 5)

[1. 1. 1. 1. 1. 1.] [0 0 0 0 0 1] inputs
[1. 1. 1. 1. 1. 1.]
[0. 1. 0. 1. 0. 1.] [1. 1. 1. 1. 1. 1.] inputs
[1. 1. 2. 2. 3. 3. 2. 2. 1. 1.]
[0. 0. 1. 0. 0. 1.] [3. 3. 2. 2. 1. 1.] inputs
[3. 3. 2. 5. 4. 3. 2. 1. 1.]


array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 2., 2., 3., 3.],
       [1., 1., 2., 3., 4., 5.]])

In [10]:
N = 3
S = 5
soldier_dist_collapsed(5, N, S, partition_matrix(N, S), out =[])

Exception: You are bad at coding >:(

In [2]:
partition_matrix(2, 3)

array([[1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 1., 1., 2.]])